### PR TITLE
Add 1fa option

### PR DESCRIPTION
**Pull request by superteece**
I had a need to use YubiKey as a 1FA option like in a similar project on Arch Linux. I've added the option for 1FA to this branch. The config file has a new option which if uncommented and set will enable 1FA.

### CODE REVIEW

**Comment by Vincent43** [comment]
@superteece FYI I plan to add debian/ubuntu support for existing Arch Linux project but didn't had the time. The runtime scripts should work out-of-the-box so this need only initramfs script + packaging. If you would be interested in working on it then I can help.

**Comment by superteece** [comment]
> 
> 
> @superteece FYI I plan to add debian/ubuntu support for existing Arch Linux project but didn't had the time. The runtime scripts should work out-of-the-box so this need only initramfs script + packaging. If you would be interested in working on it then I can help.


I looked at going that route as well and honestly knew zero about the manipulation of initramfs prior to this. Adding to yubikey-luks ended up being the simplest solution to get the capability I needed. If it gets merged then great, if not then I'll merge to my own master branch and use it as is. But I have no bandwidth at the moment to contribute to the arch project, sorry.

**Comment by nolteb** [comment]
I was able to implement non-interactive 1FA with just a couple lines of code to the current master branch (as of this posting), per: https://github.com/cornelinux/yubikey-luks/pull/65

**Comment by cornelinux** [comment]
Hi @superteece 
thank you for the PR.
I am closing this PR, since with #65 we have a newer PR which matches the code changes in the meantime and will probably do, what you want.

**Pull request closed without merging**
