### PR TITLE
Various improvements, mostly error-checking

### PR DESCRIPTION
**Pull request by Gargravarr2112**
See changelog for breakdown.

### CODE REVIEW

**Comment by Vincent43** [comment]
I have trouble with those changes. Is yubikey-luks-enroll script supposed to work if crypttab is empty?

**Comment by Gargravarr2112** [comment]
@Vincent43 er, good point, that's something I hadn't considered. Looking at the script, it would probably fail. I'll need to add a failsafe.

**Comment by uqam-fob** [comment]
There are many good and wrong things with the proposed changes.

* At first glance, no bashisms were introduced with the exception of `set -o pipefail` and `function`. Since all pipes are in subshells, the flag doesn't apply and is unnecessary. `function` is unnecessary. Also, (`#!/bin/bash`) this turns a POSIX-compliant (read: portable) script into a GNU-specific script.
* Semi-colons got to go. Java programmer or not, they are not needed and create a diff with more noise then anything.
* Lines should not be longer than 80 characters. Have you ever worked from an early initrd (with a 80x25 console screen) and had to deal with long lines like these?

That being said, I just came across this project and definitely think you have something here. The
script definitely needs love, though. I could only check for gross problems since I'm not familiar with the code. I'll take a better look tomorrow.

Also, there's some nice things in this PR too. :)

Regards

**Comment by Vincent43** [comment]
@uqam-fob thx for your comments. Any improvements welcome.

**Comment by cornelinux** [comment]
Unfortuantely I can not merge this PR with all the semicolons.
I am also not sure if we should move to bash.
In a simple shell script I personally would not to such an excessive error handling. After all the underlying commands will raise an error.

Interesting is the LuksRootDetection.
@Gargravarr2112 It would be great if you would create a new PR with the detection without all the non-functional changes. Thanks!

**Pull request closed without merging**
